### ISSUE TITLE
Using stop, wait and retry custom callbacks with Retrying causes mypy failures

### ISSUE THREAD

**Issue by hazefully** [jd/tenacity#324]
I am using custom callbacks for `stop` and `wait` in the form of functions accepting a retry state, passing them to the `Retrying` context manager, as documented in [the Custom Callbacks section](https://tenacity.readthedocs.io/en/latest/#other-custom-callbacks). With the latest version of tenacity, this is now causing `mypy` failures since `BaseRetrying` [now only accepts `wait` and `stop` callbacks](https://github.com/jd/tenacity/blob/a7f548520e4ee871ad8aeb354ecfa1a324c8ca19/tenacity/__init__.py#L228-L230) that are function objects of a class inheriting from `wait_base` and `stop_base`. The same will also happen if a `retry` custom callback was provided.

These changes were introduced in #304. 

Since wait_base and stop_base aren't exposed as part of the public API, I believe this should be updated in order to enable using `Retrying` directly with `stop`, `wait` and `retry` custom callbacks as documented.

Small example causing `mypy` failures:
``` python
import tenacity

def my_stop(retry_state: tenacity.RetryCallState) -> bool:
    return True


def my_retry(retry_state: tenacity.RetryCallState) -> bool:
    return False


def my_wait(retry_state: tenacity.RetryCallState) -> bool:
    return False


for attempt in tenacity.Retrying(retry=my_retry, wait=my_wait, stop=my_stop):
    with attempt:
        pass
```

`mypy` output:

``` shell
$ python3.9 -m mypy test.py 
test.py:15: error: Argument "retry" to "Retrying" has incompatible type "Callable[[RetryCallState], bool]"; expected "retry_base"
test.py:15: error: Argument "wait" to "Retrying" has incompatible type "Callable[[RetryCallState], bool]"; expected "wait_base"
test.py:15: error: Argument "stop" to "Retrying" has incompatible type "Callable[[RetryCallState], bool]"; expected "stop_base"
Found 3 errors in 1 file (checked 1 source file)
```

If we change the same example to use the `@retry` decorator instead of the `Retrying` context manager, `mypy` reports no errors:

``` python
import tenacity

def my_stop(retry_state: tenacity.RetryCallState) -> bool:
    return True


def my_retry(retry_state: tenacity.RetryCallState) -> bool:
    return False


def my_wait(retry_state: tenacity.RetryCallState) -> bool:
    return False

@tenacity.retry(wait=my_wait, stop=my_stop, retry=my_retry)
def retryable_function():
    pass

retryable_function()
```

`mypy` output:
```
$ python3.9 -m mypy test.py 
Success: no issues found in 1 source file
```
