### ISSUE TITLE
Tenacity only works with Tornado 4.5 or above

### ISSUE THREAD

**Issue by jslvtr** [jd/tenacity#99]
Hello! I'm running on Tornado 4.4.3, but my tests fail with the following:

```
../app/thunderflock.py:58: in <module>
    wait=wait_fixed(DatabaseRetryConfig['retry_wait_seconds']))
../.venv/lib/python3.6/site-packages/tenacity/__init__.py:95: in wrap
    elif tornado and tornado.gen.is_coroutine_function(f):
E   AttributeError: module 'tornado.gen' has no attribute 'is_coroutine_function'
```

`tornado.gen.is_coroutine_function` was added in Tornado 4.5. Would be great to display this in the README (or add support for Tornado 4.4, ideally!).

**Comment by pshchelo** [comment]
I'd actually like to see support for as far back as tornado 4.2.1 as this is the version packaged in Ubuntu Xenial LTS.

I was hit by this recently, and spent quite some time trying to understand what was the reason (OpenStack Neutron was failing to start). I tried to run OpenStack master on Xenial, and manage it with Salt, and it appears salt-common/salt-minion is dependent on python-tornado... :man_facepalming:
